# Generated by Django 3.1.2 on 2020-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_event_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=200, null=True)),
                ('mail', models.CharField(max_length=200)),
                ('group', models.ManyToManyField(to='pages.Group')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
