# Generated by Django 3.1.2 on 2020-10-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0004_auto_20201026_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
