# Generated by Django 3.1.2 on 2020-10-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201026_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prenom',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
