# Generated by Django 3.1.2 on 2020-10-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201026_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='alumni_status',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.alumni_status'),
            preserve_default=False,
        ),
    ]
