# Generated by Django 3.1.2 on 2020-10-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201026_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_status',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alumni_status',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.alumni_status'),
        ),
    ]
