# Generated by Django 3.0.5 on 2020-07-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_paid', models.DateField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
